var SERVER_URL = process.env.REACT_APP_SERVER_URL;
var SERVER_URL_USER = process.env.REACT_APP_SERVER_URL_USER;
var LISTS_BANK_URL = process.env.REACT_APP_LISTS_BANK_URL;
export { SERVER_URL, SERVER_URL_USER, LISTS_BANK_URL };
